### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by Benjamoose** [TheOddball/KoikatsuPmxExporter#1]
Hi there! I'm anxiously looking forward to this.

Is there a thread or something somewhere that I can keep up with to see progress?

Thanks for any response!

**Comment by TheOddball** [comment]
I don't know much about C#, I simply extracted the dll and put it up here for other developers to work on and have an easy place to find the plugin

**Comment by Benjamoose** [comment]
Ah darn!

Well, I appreciate the reply and clarification!

**Comment by Mek101** [comment]
Does the exporter work if compiled from this source?

**Comment by TheOddball** [comment]
> Does the exporter work if compiled from this source?

When I tried to do that, it would not build unfortunately. If you can get it to build, that would be greatly appreciated.
